import { createSlice } from "@reduxjs/toolkit";

const apartmentSlice = createSlice({
  name: "apartments",
  initialState: {
    headings: {
      id: "ID",
      address_1: "Adresse",
      address_2: "Complément d'adresse",
      zipcode: "Code postal",
      city: "Ville",
      in_management: "En gestion",
    },
    deposit_headings: {
      id: "ID",
      tenant_id: "ID Locataire",
      total_amount: "Montant total",
      paid_amount: "Montant réglé",
      status: "Status",
    },
    rent_headings: {
      id: "ID",
      tenant_id: "ID Locataire",
      total_amount: "Montant total",
      paid_amount: "Montant réglé",
      issue_date: "Date d'émission",
      due_date: "Date d'échéance",
      period: "Période",
    },

    apartment: {
      id: "#12",
      address_1: "22 rue des accacias",
      address_2: "Cedex 36",
      zipcode: "68300",
      city: "Mulhouse",
      in_management: "True",
      monthly_charges: 50.0,
      monthly_rent: 800.0,
      deposit: 850.0,
      in_management: "True",
      management_fees: 64.0,
      tenant: {
        firstname: "Jean",
        lastname: "Valjean",
        email: "jean.valjean@gmail.com",
        caf_payment: "True",
        id: "#856",
      },
      deposit_bill: [
        {
          id: "#12333",
          apartment_id: "#12",
          tenant_id: "#856",
          total_amount: 850.0,
          paid_amount: 850.0,
          paid: true,
          issue_date: Date.now(),
          due_date: Date.now(),
          deposit_amount: 850.0,
          status: "active",
          refunded: false,
        },
      ],
      rent_bills: [
        {
          id: "#12333",
          apartment_id: "#12",
          tenant_id: "#856",
          total_amount: 850.0,
          paid_amount: 850.0,
          paid: true,
          issue_date: Date.now(),
          due_date: Date.now(),
          rent_amount: 800.0,
          charges: 50.0,
          management_fees: 64,
          period: "january_2023",
        },
        {
          id: "#12333",
          apartment_id: "#12",
          tenant_id: "#856",
          total_amount: 850.0,
          paid_amount: 0.0,
          paid: false,
          issue_date: Date.now(),
          due_date: Date.now(),
          rent_amount: 800.0,
          charges: 50.0,
          management_fees: 64,
          period: "february_2023",
        },
      ],
    },

    apartments: [
      {
        id: "#12",
        address_1: "22 rue des accacias",
        address_2: "Cedex 36",
        zipcode: "68300",
        city: "Mulhouse",
        monthly_charges: 50.0,
        monthly_rent: 800.0,
        deposit: 850.0,
        in_management: "True",
        management_fees: 64.0,
      },
      {
        id: "#36",
        address_1: "16 rue des champs",
        address_2: "",
        zipcode: "67370",
        city: "Dingsheim",
        in_management: "True",
        monthly_charges: 30.0,
        monthly_rent: 600.0,
        deposit: 630.0,
        in_management: "True",
        management_fees: 48.0,
      },
    ],
  },
  reducers: {},
});

export default apartmentSlice.reducer;
